### ISSUE TITLE
Heavy bug in 1.0.3 and 1.0.4

### ISSUE THREAD

**Issue by IceLancerSR** [Kaldaien/TZF#14] opened 2015-11-22 13:30 UTC
It seems that 1.0.4 (And 1.0.3) dll's keeps working even after game is shutdown and affecting other games.
it shows 15 lines of some strange info with data taken from afterburner with title "tales of zestiria fix 1.0.4"(both 1.0.3 and 1.0.4)

It also breaks Tales game with double speed of everything , skits, movement interactions..(only 1.0.4)

P.S PC restart or logout is required to turn off "fix" i was not able to find dll hook active anywhere tho.(both 1.0.3 and 1.0.4)

Addendum.
This heavy bug is happening with 1.0.3 as well..

http://imgur.com/bFLzo2p

This is picture of what is happening
It is clearly as title shows "fix" for tales.
It will also crash some other games as well if pc is not restarted..
Game on picture is Lords of Xulima (No i did not used "fix" for this game fix is only for tales which i started and turned off before starting Lords.)

Win7x64 8gb ram, ati 6970 2gb ddr5 , intel 2500k
RTSS 640

**Comment by drdaxxy** [comment] 2015-11-22 14:25
Game running at double speed with the 1.0.4 *pre-release* is a known issue, which is why the release notes explicitly tell you not to use it except when instructed to, as it has a feature useful for testing.

I couldn't tell you why the OSD shows up in unrelated applications, though.

**Comment by IceLancerSR** [comment] 2015-11-22 14:51
The heavy bug i was referring to is dll which is not unhooked (obviously) from afterburner.
"not to use" .. i am not an idiot, i was doing test. or are you trying to say something else?

Bug is linked to 1.0.3 dll as unhooking is not working properly bugging every other game in process

**Comment by drdaxxy** [comment] 2015-11-22 15:11
Sorry, that came out wrong. We do appreciate you testing what you can, but I wanted to let you know that the 1.0.4 pre-release is not in a playable state.

And I do understand what the bug you're talking about is; this will have to be investigated, so thanks for the report.

**Comment by Kaldaien** [comment] 2015-11-26 07:15
I do not understand what "heavy" means. The OSD, on the other hand, is supposed to go away if you shut the game down properly. The way the OSD works is that opens a Shared Memory connection with RTSS and writes text there. It's designed to CLEAR that shared memory on exit so that the OSD does not persist in other programs.

I cannot duplicate or even think of any reasons this would be happening related to any changes in 1.0.3 or 1.0.4.

Be aware, you need not reboot to clear that text. You can exit RivaTuner Statistics Server and start it up again. In the worst case, I can write a tool to clear all text from RTSS with the click of a button - I'm surprised Unwinder has not already :)

**Comment by Kaldaien** [comment] 2015-12-12 09:01
This is caused by AMD hardware... or rather, the lack of me having any to test on. I am pretty sure you do not have 8 GPUs :)

I'll review this tomorrow and see what can be done.

**Comment by Kaldaien** [comment] 2016-06-13 00:39
AMD's hardware stats should be fixed in 1.4.0

**Closed by Kaldaien** 2016-06-13 00:39 UTC
Labels: question
